name: Push File Example

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  push-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create or modify a file
      run: |
        echo "This is a new file" > newfile.txt
        # You can use any shell command to create or modify files here

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit changes
      run: |
        git add newfile.txt
        git commit -m "Add newfile.txt"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git push
